name: 'Reusable Semgrep Analysis'

on:
  workflow_call:
    inputs:
      repo:
        description: 'Repository that requested the scan'
        required: true
        type: string
      paths_ignored:
        description: 'Comma delimited paths to ignore during scan'
        required: false
        type: string
        default: ''
    outputs:
      sarif-id:
        description: 'SARIF file identifier'
        value: ${{ jobs.semgrep-analysis.outputs.sarif-id }}

jobs:
  semgrep-analysis:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    outputs:
      sarif-id: ${{ steps.upload.outputs.sarif-id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          path: ${{ inputs.repo }}

      - name: Call Security Code Scanner Semgrep Action
        id: semgrep-scan
        uses: ./packages/semgrep-action
        with:
          paths_ignored: ${{ inputs.paths_ignored }}

      - name: Upload SARIF
        id: upload
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
          category: semgrep
